//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLFIGURE
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINHLUAN
    {
        public int Id { get; set; }
        public int MaFigure { get; set; }
        public string HoTen { get; set; }
        public string NoiDung { get; set; }
        public int SoSao { get; set; }
        public System.DateTime Ngay { get; set; }
    
        public virtual FIGURE FIGURE { get; set; }
    }
}
