//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLFIGURE
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIGURE
    {
        public FIGURE()
        {
            this.BINHLUANs = new HashSet<BINHLUAN>();
            this.HINHANHs = new HashSet<HINHANH>();
        }
    
        public int MaFigure { get; set; }
        public string TenFigure { get; set; }
        public Nullable<int> NamSX { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string MoTa { get; set; }
        public string AnhBia { get; set; }
        public int Loai { get; set; }
        public int NhaCungCap { get; set; }
    
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
        public virtual LOAIFIGURE LOAIFIGURE { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP1 { get; set; }
        public virtual ICollection<HINHANH> HINHANHs { get; set; }
    }
}
