//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLFIGURE
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public HoaDon()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        }
    
        public int MaHD { get; set; }
        public int MaKH { get; set; }
        public Nullable<int> MaNV { get; set; }
        public System.DateTime NgayLap { get; set; }
        public decimal TongTien { get; set; }
        public int TinhTrang { get; set; }
        public string DiaChiGiaoHang { get; set; }
        public bool DaThanhToan { get; set; }
    
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual TINHTRANG TINHTRANG1 { get; set; }
    }
}
