//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLFIGURE
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIFIGURE
    {
        public LOAIFIGURE()
        {
            this.FIGUREs = new HashSet<FIGURE>();
        }
    
        public int MaLoai { get; set; }
        public string TenLoai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<FIGURE> FIGUREs { get; set; }
    }
}
