//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLFIGURE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_FigureEntities6 : DbContext
    {
        public QL_FigureEntities6()
            : base("name=QL_FigureEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Banner> Banners { get; set; }
        public DbSet<BINHLUAN> BINHLUANs { get; set; }
        public DbSet<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public DbSet<FIGURE> FIGUREs { get; set; }
        public DbSet<HINHANH> HINHANHs { get; set; }
        public DbSet<HoaDon> HoaDons { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<LOAIFIGURE> LOAIFIGUREs { get; set; }
        public DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<TINHTRANG> TINHTRANGs { get; set; }
        public DbSet<VAITRO> VAITROes { get; set; }
    }
}
